### ISSUE TITLE
似乎是一处笔误

### ISSUE THREAD

**Issue by vpsbash** [xry111/lfs-book-i18n#18]
https://bf.mengyan1223.wang/lfs/zh_CN/11.1/chapter08/Python.html

--with-ensurepip=yes
该选项启用稳定，但在编译期成本较高的优化。

原文
--enable-optimizations
This switch enables stable, but expensive, optimizations.

**Comment by xry111** [comment]
已经在开发版本修复：https://github.com/xry111/lfs-book-i18n/commit/bb6ca3cc22e2a7ff287f5d74b537ca86e376270a#diff-a6af81a9336e3ffb435992d2871abdf3615d536687bc3b90ff890e7887556d2cR110

**Comment by xry111** [comment]
通常来说已经发布的版本不作更改，我在 https://bf.mengyan1223.wang/lfs/zh_CN/ 加了一个勘误链接。
