### ISSUE TITLE
网站上的 wget-list、md5sums 与 lfs 网站不一致

### ISSUE THREAD

**Issue by billchenchina** [xry111/lfs-book-i18n#2]
你好，目前遇到了两个问题

1. 您网站上的 [wget-list](https://bf.mengyan1223.wang/lfs/zh_CN/10.0/wget-list) 与 [lfs/downloads/10.0/wget-list](http://www.linuxfromscratch.org/lfs/downloads/10.0/wget-list) 文件内容不一致
2. 您网站上的 [wget-list](https://bf.mengyan1223.wang/lfs/zh_CN/10.0/wget-list) 无法与您网站上的 [md5sums](https://bf.mengyan1223.wang/lfs/zh_CN/10.0/md5sums) 文件 check 通过。

请检查一下，（或者也可能是更新问题？），谢谢

**Comment by xry111** [comment]
确认这个问题是存在的。

LFS 官网给的 `wget-list` 和 `md5sum` 会同时下载和验证 systemd 和 sysvinit 两个版本的手册使用的软件包，而从 XML 生成出来的只会下载一个版本 (例如，如果 `make` 的时候使用了 `REV=systemd` 就不会包含 `sysvinit-2.97.tar.gz`。

我先去编辑群问一下为什么官方提供的 `wget-list` 和 `md5sum` 要同时包含两种版本的软件包……

**Comment by xry111** [comment]
10.0 的 wget-list 不知道为啥变成某个后续的 development 版本的了…… 10.0 是迁移到 GitHub 前自动生成的，可能当时用的 hook 有问题。

现在干脆在 GitHub 上重新弄一下，顺便为 10.1 的发布做准备 :)

**Comment by billchenchina** [comment]
> 10.0 的 wget-list 不知道为啥变成某个后续的 development 版本的了…… 10.0 是迁移到 GitHub 前自动生成的，可能当时用的 hook 有问题。
> 
> 现在干脆在 GitHub 上重新弄一下，顺便为 10.1 的发布做准备 :)

对的，是 development 版本。

感谢XD

**Comment by xry111** [comment]
10.0 and 10.0-systemd 已经在 d2e19e1 重新生成。

感谢报告 :+1:
