### ISSUE TITLE
`chapter07/libstdc++-pass2.po` 第133行有一处容易引起误解

### ISSUE THREAD

**Issue by ClearPlume** [xry111/lfs-book-i18n#21]
https://github.com/xry111/lfs-book-i18n/blob/8f9c47792dc571119ddf2249d8441811da3d208d/zh_CN/chapter07/libstdc%2B%2B-pass2.po#L133

我第一眼把`-O2`当成了`-02`，写的时候感觉有点奇怪“怎么是个八进制数字”，之后make报错我才意识到是大写字母`O`，不是阿拉伯数字`0`

建议在这里加一个类似于“注意”的东西特别说明一下

**Comment by xry111** [comment]
我看看能不能把 PDF 的字体换一下，这个 PDF 的字体确实没法区分 O 和 0。

对于 HTML 来说字体是浏览器设置决定的，可以在英文版里面加个说明然后再翻译过来。

**Comment by xry111** [comment]
Fixed: https://github.com/xry111/lfs-book-i18n/commit/7f8a9fccd568ab9b0e038a6392b7fb8537b60f69#diff-9caf1774423fae146acdf9238c93d27af7d9056bd2b3a483dd7e75ca45cb651dR81
