### ISSUE TITLE
在手册"6.3. Ncurses-6.3"的命令中 gawk 的拼写是否有问题？

### ISSUE THREAD

**Issue by CASSHERNTsui** [xry111/lfs-book-i18n#24]
![image](https://user-images.githubusercontent.com/46068677/208230936-39015f6e-87c1-46f4-b859-865e374bb484.png)
我看了9.0手册与11.2的手册，发现配置时优先查找 gawk 命令都是
“sed -i s/mawk// configure"

想请问一下这里的mawk是否是一个拼写错误

**Comment by xry111** [comment]
该命令从 configure 中尝试使用的 awk 程序列表中删除 mawk，因此可以保证优先使用 gawk。

**Comment by CASSHERNTsui** [comment]
> 



> 该命令从配置中尝试使用的awk 程序列表中删除mawk，因此可以保证优先使用gawk。

:)thanks

**Comment by CASSHERNTsui** [comment]
> 该命令从 configure 中尝试使用的 awk 程序列表中删除 mawk，因此可以保证优先使用 gawk。

查阅了一下sed语法后发现这里是将configure源文件中的mawk都换成"没有"(删除掉）了。提了一个很蠢的问题。哈哈哈
