### ISSUE TITLE
构建过程的其他细节/Other procedural details 一些typo

### ISSUE THREAD

**Issue by Winson-Huang** [xry111/lfs-book-i18n#25]
这一节的倒数第三自然段，

> 然后是[第 6 章](https://lfs.xry111.site/zh_CN/11.2-systemd/chapter06/chapter06.html)中那些需要自身才能构建的程序后。

原文为：

> followed in [Chapter 6](https://www.linuxfromscratch.org/lfs/view/stable/chapter06/chapter06.html) by all the programs that need themselves to be built.

应该去掉最后一个“后”字。

倒数第二自然段，

> 在[第 6 章](https://lfs.xry111.site/zh_CN/11.2-systemd/chapter06/chapter06.html)一节的末尾，

建议将“一节”去掉。

**Comment by Winson-Huang** [comment]
我指的是[11.2版本](https://lfs.xry111.site/zh_CN/11.2-systemd/)，不是正在开发的版本。

**Comment by xry111** [comment]
已经在开发版本修复，我们不更改已经发布的版本。

**Comment by Winson-Huang** [comment]
OK，本意就是希望放在 errdata 中。
