### ISSUE TITLE
一个小小bug

### ISSUE THREAD

**Issue by bkdp** [xry111/lfs-book-i18n#33]
非常感谢大佬做的翻译工作，按照手册我已经顺利装好lfs，使用手册的过程中发现一个小错误，在第《11 章 收尾工作》 下面《11.5. 开始使用新构建的 LFS》底下的11.5.2.2. 使用 ssh 远程工作 里面的 wget 外部链接是错的，指向了openssh的页面地址，对照英文版之后应指向：https://www.linuxfromscratch.org/blfs/view/12.0/basicnet/wget.html

错误页面的地址：
https://lfs.xry111.site/zh_CN/12.0/chapter11/afterlfs.html

**Comment by xry111** [comment]
已经在主分支 (1635411f25c2b6857bea322d3e706a0580feab94) 修复，和英文版手册一样，我们并不更改已经发布的手册。
