### ISSUE TITLE
Ncurses的翻译

### ISSUE THREAD

**Issue by lxvalencia** [xry111/lfs-book-i18n#7]
英文版：
The Ncurses package contains libraries for terminal-independent handling of character screens.
中文版：
Ncurses 软件包包含终端无关的字符屏幕处理库。
推荐的翻译：
Ncurses 软件包包含终端有关的字符屏幕处理库。

非常感谢您。

**Comment by xry111** [comment]
terminal-independant 直译过来是终端无关，但是这里直接译成这样确实不对（一股机翻味，应该检讨）

我再想想怎么译比较好……

**Comment by xry111** [comment]
已经改为 `Ncurses 软件包包含使用时不需考虑终端特性的字符屏幕处理函数库。`

还有更好的建议吗？

**Comment by lxvalencia** [comment]
这个很不错！谢谢
